{% set name = "server-thread" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d89f80048b1c2ea311ab10665e955d8a075c7a823a06c80563714aff42c4ec12

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - setuptools
    - scooby
    - uvicorn
    - werkzeug

test:
  imports:
    - server_thread

about:
  home: https://github.com/banesullivan/server-thread
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Launch a WSGIApplication in a background thread with werkzeug
  description: |
    Launch a WSGIApplication in a background thread with werkzeug
  doc_url: https://github.com/banesullivan/server-thread/blob/main/README.md
  dev_url: https://github.com/banesullivan/server-thread

extra:
  recipe-maintainers:
    - banesullivan
